#cloud-config
hostname: ${hostname}

# Install packages
packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - iotop
  - sysstat
  - python3
  - python3-pip

# Create deploy user
users:
  - name: deploy
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_key}

# Disable swap
runcmd:
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

# Set timezone
timezone: UTC

# Enable automatic security updates
package_update: true
package_upgrade: true
