---
# RBAC for Vault to access Kubernetes API
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: adplatform
---
# Service Account for applications to access Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: adplatform
---
# ClusterRole for Vault auth
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-token-creator
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
# ClusterRoleBinding for Vault auth
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-token-creator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-token-creator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: adplatform
