---
# Install k3s Kubernetes cluster

- name: Install k3s on control plane
  hosts: control_plane
  become: yes

  tasks:
    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"

    - name: Install k3s server
      shell: |
        INSTALL_K3S_EXEC="server --write-kubeconfig-mode=644 --disable=traefik --flannel-backend=none --disable-network-policy" \
        /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Get k3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Get k3s server IP
      set_fact:
        k3s_url: "https://{{ ansible_default_ipv4.address }}:6443"

    - name: Save token for workers
      set_fact:
        k3s_token_value: "{{ k3s_token.content | b64decode | trim }}"

- name: Install k3s on worker nodes
  hosts: data_plane,edge
  become: yes

  tasks:
    - name: Download k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"

    - name: Install k3s agent
      shell: |
        K3S_URL="{{ hostvars[groups['control_plane'][0]].k3s_url }}" \
        K3S_TOKEN="{{ hostvars[groups['control_plane'][0]].k3s_token_value }}" \
        /tmp/k3s-install.sh agent
      args:
        creates: /usr/local/bin/k3s

- name: Install Helm and Cilium
  hosts: control_plane
  become: yes

  tasks:
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Add Cilium Helm repo
      become_user: deploy
      shell: |
        helm repo add cilium https://helm.cilium.io/
        helm repo update
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install Cilium
      become_user: deploy
      shell: |
        helm install cilium cilium/cilium --version 1.14.0 \
          --namespace kube-system \
          --set global.etcd.enabled=false
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
